import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		// Embedded semantic-tagging model + WASM runtime (see fetch-model-assets.mjs)
		// are base64-encoded straight into main.js so the plugin needs no extra
		// files or network access to run the "Semantic tags" command.
		".onnx": "binary",
		".wasm": "binary",
		".txt": "text",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
